services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    hostname: mysql
    environment:
      MYSQL_DATABASE: 'vendas'
      MYSQL_USER: 'vendas'
      MYSQL_PASSWORD: 'quarkus_test'
      MYSQL_ROOT_PASSWORD: 'quarkus_test'
    ports:
      - 3307:3306
    expose:
      - "3307"

  redis:
    container_name: redis
    image: redis
    restart: always
    hostname: redis
    ports:
      - 6379:6379
    expose:
      - "6379"

  jms:
    container_name: jms
    image: vromero/activemq-artemis:2.11.0-alpine
    environment:
      ARTEMIS_USERNAME: quarkus
      ARTEMIS_PASSWORD: quarkus
    restart: always
    ports:
      - 8161:8161
      - 61616:61616
      - 5672:5672
    expose:
      - "6161"
      - "8161"
      - "61616"
      - "5672"

